/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.clusterclient.ui;

import com.clusterclient.EnvironmentRepository;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author HolleranJ
 */
public class ClusterRequestDialog extends javax.swing.JDialog {

    private final EnvironmentRepository environmentRepository;
    private String environmentSelected = "";
    
    /**
     * Creates new form ClusterRequestDialog
     */ 
    public ClusterRequestDialog(java.awt.Frame parent, EnvironmentRepository environmentRepository) {
        super(parent, true);
        this.environmentRepository = environmentRepository;
        initComponents();
        setLocationRelativeTo(parent);
        setVisible(true);
    }

    public String getEnvironment() {
        return environmentSelected;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configPanel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        envComboBox = new javax.swing.JComboBox();
        controlsPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Server Cluster");
        setModal(true);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        label.setText("Please select Cluster:");
        configPanel.add(label);

        envComboBox.setModel(new DefaultComboBoxModel(environmentRepository.findAllEnvironments().toArray()));
        configPanel.add(envComboBox);

        getContentPane().add(configPanel);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonPressed(evt);
            }
        });
        controlsPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonPressed(evt);
            }
        });
        controlsPanel.add(cancelButton);

        getContentPane().add(controlsPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonPressed
        environmentSelected = (String) envComboBox.getSelectedItem();
        dispose();
    }//GEN-LAST:event_okButtonPressed

    private void cancelButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonPressed
        dispose();
    }//GEN-LAST:event_cancelButtonPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel configPanel;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JComboBox envComboBox;
    private javax.swing.JLabel label;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
